/**
 * FreshMart demo dataset — mirrors the RoadmapAI analytics mockup exactly
 * so Overview UI/UX matches the reference dashboard.
 */
import type { DashboardData, IssueCluster } from "@/lib/types";

export const DEMO_WORKSPACE = {
  name: "FreshMart Supermarket Pro",
  industry: "Retail / Grocery",
  userName: "Arjun Kumar",
  userRole: "Product Manager",
};

export const DEMO_ASSUMPTIONS = {
  monthly_customers: 20000,
  avg_revenue_per_user: 450,
  premium_pct: 18,
  currency: "INR",
  configured: true,
};

export const DEMO_ISSUES: IssueCluster[] = [
  {
    id: "demo-1",
    session_id: "demo",
    issue_key: "checkout_waiting_time",
    category: "Checkout",
    business_area: "Store Operations",
    description: "Long queues at billing counters during peak hours",
    review_count: 387,
    avg_severity: 4.6,
    avg_confidence: 0.92,
    avg_sentiment: -0.72,
    premium_user_count: 86,
    priority_score: 91,
    priority_rank: 1,
    revenue_at_risk: 142000,
    estimated_revenue_impact: 142000,
    affected_customers: 1862,
    customer_reach_percentage: 9.3,
    platforms: ["qr", "app_store"],
    sample_reviews: [
      "Waited almost 30 mins at checkout during evening rush.",
      "Only two counters open — lost customers every night.",
    ],
    decision_pillars: {
      revenue_impact: 91,
      customer_reach: 9.3,
      severity: 92,
      premium_users: 70,
      customer_tier: 70,
      revenue_pct: 40,
      reach_pct: 28,
      severity_pct: 20,
      premium_pct: 12,
      estimated_revenue_impact: 142000,
      affected_customers: 1862,
      customer_reach_percentage: 9.3,
      severity_risk_factor: 0.7,
      revenue_formula:
        "estimated_revenue_impact = affected_customers × ARPU × severity_risk_factor",
      formula: "Priority = Revenue×0.35 + Reach×0.30 + Severity×0.20 + Tier×0.15",
    },
  },
  {
    id: "demo-2",
    session_id: "demo",
    issue_key: "payment_failure",
    category: "Payment",
    business_area: "Payments",
    description: "UPI and card declines at self-checkout kiosks",
    review_count: 241,
    avg_severity: 4.4,
    avg_confidence: 0.9,
    avg_sentiment: -0.68,
    premium_user_count: 54,
    priority_score: 76,
    priority_rank: 2,
    revenue_at_risk: 98000,
    estimated_revenue_impact: 98000,
    affected_customers: 1240,
    customer_reach_percentage: 6.2,
    platforms: ["app_store", "csv"],
    sample_reviews: [
      "UPI payment failed twice at self-checkout.",
      "Card keeps getting declined at kiosk.",
    ],
    decision_pillars: {
      revenue_impact: 76,
      customer_reach: 6.2,
      severity: 88,
      premium_users: 55,
      customer_tier: 55,
      revenue_pct: 38,
      reach_pct: 26,
      severity_pct: 22,
      premium_pct: 14,
      estimated_revenue_impact: 98000,
      affected_customers: 1240,
      customer_reach_percentage: 6.2,
    },
  },
  {
    id: "demo-3",
    session_id: "demo",
    issue_key: "app_crash_on_launch",
    category: "Reliability",
    business_area: "Mobile App",
    description: "App crashes on launch for Android 13+ devices",
    review_count: 168,
    avg_severity: 4.2,
    avg_confidence: 0.88,
    avg_sentiment: -0.61,
    premium_user_count: 41,
    priority_score: 63,
    priority_rank: 3,
    revenue_at_risk: 54000,
    estimated_revenue_impact: 54000,
    affected_customers: 890,
    customer_reach_percentage: 4.5,
    platforms: ["app_store"],
    sample_reviews: [
      "App crashes every time I open it after update.",
      "Can't even log in — force closes immediately.",
    ],
    decision_pillars: {
      revenue_impact: 63,
      customer_reach: 4.5,
      severity: 84,
      premium_users: 48,
      customer_tier: 48,
      revenue_pct: 36,
      reach_pct: 24,
      severity_pct: 24,
      premium_pct: 16,
      estimated_revenue_impact: 54000,
      affected_customers: 890,
      customer_reach_percentage: 4.5,
    },
  },
  {
    id: "demo-4",
    session_id: "demo",
    issue_key: "dark_mode_missing",
    category: "UX",
    business_area: "UI",
    description: "Customers request dark theme for late-night shopping",
    review_count: 129,
    avg_severity: 2.4,
    avg_confidence: 0.82,
    avg_sentiment: -0.22,
    premium_user_count: 22,
    priority_score: 41,
    priority_rank: 4,
    revenue_at_risk: 22000,
    estimated_revenue_impact: 22000,
    affected_customers: 640,
    customer_reach_percentage: 3.2,
    platforms: ["qr", "csv"],
    sample_reviews: [
      "Please add dark mode — hard to use at night.",
      "Bright white screen hurts eyes after 10pm.",
    ],
    decision_pillars: {
      revenue_impact: 41,
      customer_reach: 3.2,
      severity: 48,
      premium_users: 30,
      customer_tier: 30,
      revenue_pct: 30,
      reach_pct: 28,
      severity_pct: 22,
      premium_pct: 20,
      estimated_revenue_impact: 22000,
      affected_customers: 640,
      customer_reach_percentage: 3.2,
    },
  },
  {
    id: "demo-5",
    session_id: "demo",
    issue_key: "slow_checkout_flow",
    category: "Checkout",
    business_area: "Online Orders",
    description: "Online checkout takes too many steps to complete",
    review_count: 94,
    avg_severity: 3.1,
    avg_confidence: 0.8,
    avg_sentiment: -0.4,
    premium_user_count: 18,
    priority_score: 34,
    priority_rank: 5,
    revenue_at_risk: 18000,
    estimated_revenue_impact: 18000,
    affected_customers: 510,
    customer_reach_percentage: 2.6,
    platforms: ["app_store"],
    sample_reviews: [
      "Too many screens before I can pay online.",
      "Abandoned cart — checkout flow is exhausting.",
    ],
    decision_pillars: {
      revenue_impact: 34,
      customer_reach: 2.6,
      severity: 62,
      premium_users: 28,
      customer_tier: 28,
      revenue_pct: 32,
      reach_pct: 26,
      severity_pct: 24,
      premium_pct: 18,
      estimated_revenue_impact: 18000,
      affected_customers: 510,
      customer_reach_percentage: 2.6,
    },
  },
];

export const DEMO_DASHBOARD: DashboardData = {
  session_id: "demo",
  source: "multi",
  filename: "freshmart_demo.csv",
  is_demo_data: true,
  total_reviews: 2041,
  actionable_reviews: 1680,
  revenue_at_risk: 284000,
  estimated_revenue_impact_total: 284000,
  top_priority_issue: DEMO_ISSUES[0],
  most_requested_feature: DEMO_ISSUES[3],
  executive_summary:
    "Checkout waiting time is the #1 revenue leak. Fix peak-hour staffing and lane capacity first.",
  headline_insights: [
    "Checkout queues drive ₹1.42L monthly risk",
    "Payment failures cluster at self-checkout",
    "Sentiment is 53% negative across channels",
  ],
  ai_recommendation:
    "Open 2 more peak-hour lanes and staff express checkout before 6–9pm — highest ROI this sprint.",
  issues: DEMO_ISSUES,
  analysis_health: {
    quality_score: 91,
    total_processed: 2041,
    spam_skipped: 48,
    duplicates_removed: 112,
    ai_confidence: 94,
  },
  kpis: {
    total_estimated_revenue_impact: 284000,
    revenue_at_risk_critical_high: 240000,
    customers_affected: 5142,
    critical_issue_count: 18,
    issue_count: 5,
  },
  business_assumptions: {
    ...DEMO_ASSUMPTIONS,
    disclaimer:
      "Figures are Estimated Revenue Impact / at Risk based on workspace assumptions — not actual revenue lost.",
  },
  fix_first: {
    issue_key: "checkout_waiting_time",
    title: "Checkout Waiting Time",
    why: "Highest estimated revenue impact and largest affected customer base.",
    recommendation: "Fix Checkout Waiting Time First.",
    estimated_revenue_impact: 142000,
    affected_customers: 1862,
    priority_score: 91,
  },
  sentiment_distribution: {
    negative_pct: 53.2,
    positive_pct: 35.2,
    neutral_pct: 11.5,
    total: 2041,
  },
};

export const DEMO_HEALTH = {
  total_feedback: 2041,
  feedback_this_week: 186,
  engagement_mode: "improvement",
  points_issued: 1240,
  top_source: "qr",
  most_repeated_issue: "checkout_waiting_time",
  sentiment_distribution: {
    negative_pct: 53.2,
    positive_pct: 35.2,
    neutral_pct: 11.5,
  },
};

export const DEMO_RECENT = [
  {
    id: "r1",
    text: "Waited almost 30 mins at checkout during evening rush. Only two counters open!",
    category: "Checkout",
    rating: 1,
    time: "2m ago",
    tone: "neg" as const,
  },
  {
    id: "r2",
    text: "UPI payment failed twice at self-checkout. Had to leave items behind.",
    category: "Payment",
    rating: 2,
    time: "8m ago",
    tone: "neg" as const,
  },
  {
    id: "r3",
    text: "Fresh produce section was well stocked today — great improvement!",
    category: "Inventory",
    rating: 5,
    time: "14m ago",
    tone: "pos" as const,
  },
  {
    id: "r4",
    text: "App crashes on launch after the latest update. Can't order at all.",
    category: "Reliability",
    rating: 1,
    time: "22m ago",
    tone: "neg" as const,
  },
  {
    id: "r5",
    text: "App is fine overall, but finding offers is confusing.",
    category: "UX",
    rating: 3,
    time: "41m ago",
    tone: "neu" as const,
  },
];

export const DEMO_TREND = [
  { day: "Aug 02", value: 198000 },
  { day: "Aug 03", value: 246000 },
  { day: "Aug 04", value: 218000 },
  { day: "Aug 05", value: 312000 },
  { day: "Aug 06", value: 268000 },
  { day: "Aug 07", value: 356000 },
  { day: "Aug 08", value: 284000 },
];
