"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { getLatestAnalysis } from "@/lib/business-api";
import { getSprint } from "@/lib/api";

// Flexible local interface — handles both API shape and types.ts shape
interface Story {
  id?: string;
  title?: string;
  user_story?: string;    // types.ts field name
  description?: string;   // alternative field name
  acceptance_criteria?: string[];
  story_points?: number;
  priority?: string;
  linked_issue?: string;  // types.ts field name
  issue_key?: string;     // alternative field name
  effort?: string;
}

const PRIORITY_COLOR: Record<string, string> = {
  Critical: "bg-red-500/15 text-red-400 border-red-500/25",
  critical: "bg-red-500/15 text-red-400 border-red-500/25",
  High:     "bg-amber-500/15 text-amber-400 border-amber-500/25",
  high:     "bg-amber-500/15 text-amber-400 border-amber-500/25",
  Medium:   "bg-blue-500/15 text-blue-400 border-blue-500/25",
  medium:   "bg-blue-500/15 text-blue-400 border-blue-500/25",
  Low:      "bg-slate-500/15 text-slate-400 border-slate-500/25",
  low:      "bg-slate-500/15 text-slate-400 border-slate-500/25",
};

export default function WorkspaceSprintPage() {
  const params     = useParams();
  const businessId = params.business_id as string;

  const [stories, setStories]     = useState<Story[]>([]);
  const [sessionId, setSessionId] = useState<string | null>(null);
  const [loading, setLoading]     = useState(true);
  const [error, setError]         = useState<string | null>(null);

  useEffect(() => {
    const load = async () => {
      try {
        const latest = await getLatestAnalysis(businessId);
        if (!latest.has_analysis || !latest.session_id) {
          setError("No analysis available. Run an analysis first to generate a sprint plan.");
          return;
        }
        setSessionId(latest.session_id);
        const data = await getSprint(latest.session_id);
        // Sprint data: { sprint: { stories: [...] } } or { sprint: [...] }
        const sprintData = data.sprint as unknown;
        let storyList: Story[] = [];
        if (Array.isArray(sprintData)) {
          storyList = sprintData as Story[];
        } else if (sprintData && typeof sprintData === "object") {
          storyList = (sprintData as { stories?: Story[] }).stories || [];
        }
        setStories(storyList);
      } catch (e: unknown) {
        setError(e instanceof Error ? e.message : "Failed to load sprint plan");
      } finally {
        setLoading(false);
      }
    };
    load();
  }, [businessId]);

  if (loading) return (
    <div className="flex items-center justify-center min-h-[60vh]">
      <div className="w-6 h-6 border-2 border-indigo-500/30 border-t-indigo-500 rounded-full animate-spin" />
    </div>
  );

  if (error) return (
    <div className="p-6 max-w-2xl mx-auto">
      <div className="rounded-2xl border border-indigo-500/15 bg-indigo-500/5 p-8 text-center">
        <p className="text-4xl mb-4">⚡</p>
        <h2 className="text-lg font-bold text-slate-100 mb-2">Sprint Plan Not Available</h2>
        <p className="text-sm text-slate-400 mb-6">{error}</p>
        <Link href="/" className="px-5 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-sm font-bold transition-colors no-underline">
          🚀 Upload Feedback First
        </Link>
      </div>
    </div>
  );

  const totalPoints       = stories.reduce((s, x) => s + (x.story_points || 0), 0);
  const highPriorityCount = stories.filter(s =>
    ["High", "high", "Critical", "critical"].includes(s.priority || "")
  ).length;

  return (
    <div className="p-6 max-w-4xl mx-auto">
      <div className="flex items-center justify-between flex-wrap gap-4 mb-8">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="text-xl">⚡</span>
            <h1 className="text-xl font-black text-slate-100">Sprint 1 Plan</h1>
          </div>
          <p className="text-xs text-slate-500">{stories.length} stories · {totalPoints} story points · Generated by Decision Engine</p>
        </div>
        <div className="flex gap-2">
          {sessionId && (
            <Link
              href={`/dashboard/${sessionId}/sprint`}
              className="px-3.5 py-2 rounded-xl border border-white/8 hover:border-white/15 text-slate-300 text-xs font-semibold transition-colors no-underline"
            >
              Full View + Jira Export →
            </Link>
          )}
        </div>
      </div>

      {/* Summary row */}
      <div className="grid grid-cols-3 gap-4 mb-6">
        {[
          { label: "Total Stories",  value: stories.length },
          { label: "Story Points",   value: totalPoints },
          { label: "High Priority",  value: highPriorityCount },
        ].map(m => (
          <div key={m.label} className="rounded-2xl border border-white/7 bg-[#0d0f1a] p-4 text-center">
            <p className="text-2xl font-black font-mono text-slate-100">{m.value}</p>
            <p className="text-[10px] text-slate-500 uppercase tracking-wider mt-1">{m.label}</p>
          </div>
        ))}
      </div>

      {/* Stories */}
      <div className="space-y-3">
        {stories.map((story, i) => {
          const body     = story.description || story.user_story || "";
          const issueRef = story.issue_key || story.linked_issue;
          const storyId  = story.id || `S${String(i + 1).padStart(2, "0")}`;
          const priority = story.priority || "Medium";
          return (
            <div key={`${storyId}-${i}`} className="rounded-2xl border border-white/7 bg-[#0d0f1a] p-5 hover:border-indigo-500/20 transition-all">
              <div className="flex items-start gap-3 flex-wrap mb-3">
                <span className="font-mono text-[10px] text-slate-600 shrink-0 mt-1">{storyId}</span>
                <span className={`px-2.5 py-0.5 rounded-full border text-[10px] font-bold shrink-0 ${PRIORITY_COLOR[priority] || PRIORITY_COLOR.Medium}`}>
                  {priority.toUpperCase()}
                </span>
                <span className="ml-auto px-2.5 py-0.5 rounded-lg bg-indigo-500/10 border border-indigo-500/20 text-indigo-300 text-[10px] font-mono font-bold">
                  {story.story_points || 0}sp
                </span>
              </div>
              <h3 className="text-sm font-bold text-slate-100 mb-2">{story.title}</h3>
              {body && <p className="text-xs text-slate-400 leading-relaxed mb-3">{body}</p>}
              {story.acceptance_criteria && story.acceptance_criteria.length > 0 && (
                <ul className="space-y-1 mb-3">
                  {story.acceptance_criteria.map((c, j) => (
                    <li key={j} className="flex items-start gap-2 text-[11px] text-slate-500">
                      <span className="text-emerald-500 shrink-0">✓</span> {c}
                    </li>
                  ))}
                </ul>
              )}
              {issueRef && (
                <div className="flex items-center gap-2">
                  <span className="text-[10px] text-slate-600 uppercase tracking-wider">Linked Issue:</span>
                  <span className="text-[10px] font-mono text-indigo-400 bg-indigo-500/8 border border-indigo-500/15 px-2 py-0.5 rounded">{issueRef}</span>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}
