"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import Link from "next/link";
import { getLatestAnalysis } from "@/lib/business-api";
import { getRoadmap } from "@/lib/api";

// Local interface that matches both the API shape and the types.ts shape
interface RoadmapWeek {
  week: number;
  theme: string;
  // API may return 'tasks' (new shape) or 'issues' (types.ts shape)
  tasks?: string[];
  issues?: string[];
  outcome?: string;
  rationale?: string;
  effort?: string;
}

export default function WorkspaceRoadmapPage() {
  const params     = useParams();
  const businessId = params.business_id as string;

  const [roadmap, setRoadmap]     = useState<RoadmapWeek[]>([]);
  const [sessionId, setSessionId] = useState<string | null>(null);
  const [loading, setLoading]     = useState(true);
  const [error, setError]         = useState<string | null>(null);

  useEffect(() => {
    const load = async () => {
      try {
        const latest = await getLatestAnalysis(businessId);
        if (!latest.has_analysis || !latest.session_id) {
          setError("No analysis available. Run an analysis first to generate a roadmap.");
          return;
        }
        setSessionId(latest.session_id);
        const data = await getRoadmap(latest.session_id);
        setRoadmap(data.roadmap || []);
      } catch (e: unknown) {
        setError(e instanceof Error ? e.message : "Failed to load roadmap");
      } finally {
        setLoading(false);
      }
    };
    load();
  }, [businessId]);

  if (loading) return (
    <div className="flex items-center justify-center min-h-[60vh]">
      <div className="w-6 h-6 border-2 border-indigo-500/30 border-t-indigo-500 rounded-full animate-spin" />
    </div>
  );

  if (error) return (
    <div className="p-6 max-w-2xl mx-auto">
      <div className="rounded-2xl border border-indigo-500/15 bg-indigo-500/5 p-8 text-center">
        <p className="text-4xl mb-4">🗺️</p>
        <h2 className="text-lg font-bold text-slate-100 mb-2">Roadmap Not Available</h2>
        <p className="text-sm text-slate-400 mb-6">{error}</p>
        <Link href="/" className="px-5 py-2.5 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white text-sm font-bold transition-colors no-underline">
          🚀 Upload Feedback First
        </Link>
      </div>
    </div>
  );

  const colors = ["indigo", "cyan", "violet", "emerald", "amber", "rose"];

  return (
    <div className="p-6 max-w-4xl mx-auto">
      <div className="flex items-center justify-between flex-wrap gap-4 mb-8">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="text-xl">🗺️</span>
            <h1 className="text-xl font-black text-slate-100">Product Roadmap</h1>
          </div>
          <p className="text-xs text-slate-500">6-week execution plan generated by the Decision Engine.</p>
        </div>
        <div className="flex gap-2">
          <Link href={`/business/${businessId}/sprint`} className="px-3.5 py-2 rounded-xl border border-white/8 hover:border-white/15 text-slate-300 text-xs font-semibold transition-colors no-underline">
            ⚡ Sprint Plan →
          </Link>
          {sessionId && (
            <Link href={`/dashboard/${sessionId}/roadmap`} className="px-3.5 py-2 rounded-xl border border-white/8 hover:border-white/15 text-slate-300 text-xs font-semibold transition-colors no-underline">
              Full View →
            </Link>
          )}
        </div>
      </div>

      {/* Timeline */}
      <div className="relative">
        {/* Vertical line */}
        <div className="absolute left-5 top-6 bottom-6 w-px bg-white/6 hidden sm:block" />

        <div className="space-y-5">
          {roadmap.map((week, i) => {
            const c = colors[i % colors.length];
            return (
              <div key={week.week} className="relative sm:pl-14">
                {/* Node */}
                <div className={`absolute left-1 sm:left-1 top-5 w-8 h-8 rounded-xl bg-${c}-600 flex items-center justify-center text-xs font-black text-white shadow-[0_0_16px_rgba(99,102,241,0.3)] hidden sm:flex`}>
                  W{week.week}
                </div>

                <div className={`rounded-2xl border border-white/7 bg-[#0d0f1a] p-5 hover:border-${c}-500/25 transition-all`}>
                  <div className="flex items-start gap-3 flex-wrap mb-3">
                    <span className={`sm:hidden px-2.5 py-1 rounded-lg bg-${c}-500/15 text-${c}-400 text-[10px] font-black border border-${c}-500/25`}>W{week.week}</span>
                    <div>
                      <p className={`text-sm font-bold text-slate-100`}>{week.theme}</p>
                      <p className={`text-[10px] font-bold uppercase tracking-widest text-${c}-400 mt-0.5`}>Week {week.week}</p>
                    </div>
                  </div>
                  <ul className="space-y-1.5 mb-4">
                    {((week.tasks || week.issues) || []).map((task, j) => (
                      <li key={j} className="flex items-start gap-2 text-xs text-slate-400">
                        <span className={`text-${c}-400 mt-0.5 shrink-0`}>▸</span>
                        {task}
                      </li>
                    ))}
                  </ul>
                  {(week.outcome || week.rationale) && (
                    <div className={`flex items-center gap-2 p-2.5 rounded-lg bg-${c}-500/6 border border-${c}-500/12`}>
                      <span className="text-emerald-400 text-sm shrink-0">✓</span>
                      <p className="text-[11px] text-slate-400 italic">{week.outcome || week.rationale}</p>
                    </div>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}
